site_name: RMMR Group Docs
theme: readthedocs

nav:
  - Introduction: index.md
  - Writing Documentation: writing_docs.md
  - Group Website: website.md
  - Ex Vivo Hemisphere Scanning: exvivo_hemi.md
  - Using nix Package Manager: using_nix.md
  - Using the PMACS cluster : using_pmacs.md
  - Programming the Scanner with IDEA: idea_vms.md
